"""empty message

Revision ID: 3a345c210c9d
Revises: a1529c22639d
Create Date: 2024-04-24 11:27:37.394382

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3a345c210c9d"
down_revision: Union[str, None] = "a1529c22639d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "full_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("full_name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
