"""empty message

Revision ID: 4d32aadfe444
Revises: 8e4d0d7fbc90
Create Date: 2024-05-03 17:31:44.626788

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4d32aadfe444"
down_revision: Union[str, None] = "8e4d0d7fbc90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
