"""empty message

Revision ID: 8e4d0d7fbc90
Revises: 3a345c210c9d
Create Date: 2024-05-01 16:45:13.018336

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8e4d0d7fbc90"
down_revision: Union[str, None] = "3a345c210c9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_email", table_name="users")
    op.drop_column("users", "disabled")
    op.drop_column("users", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "users", sa.Column("disabled", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.create_index("ix_users_email", "users", ["email"], unique=False)
    # ### end Alembic commands ###
