"""empty message

Revision ID: 9df48b28986a
Revises: 4fd2dfd73f76
Create Date: 2024-04-23 21:23:59.520032

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9df48b28986a"
down_revision: Union[str, None] = "4fd2dfd73f76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "username", nullable=True)
    op.alter_column("users", "full_name", nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "username", nullable=False)
    op.alter_column("users", "full_name", nullable=False)
    # ### end Alembic commands ###
